
import sys, os
import numpy as np
import math
sys.path.insert (0, '/home/plinio/puma-simulator/include/')
sys.path.insert (0, '/home/plinio/puma-simulator/src/')
sys.path.insert (0, '/home/plinio/puma-simulator/')
from data_convert import *
from instrn_proto import *
from tile_instrn_proto import *
dict_temp = {}
dict_list = []
i_temp = i_send(mem_addr=272, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=240, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=144, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=112, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=16, vtile_id=0, send_width=16, target_addr=2, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=0, send_width=16, target_addr=2, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=1008, vtile_id=0, send_width=16, target_addr=2, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=288, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=160, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=32, vtile_id=0, send_width=16, target_addr=2, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=304, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=176, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=48, vtile_id=0, send_width=16, target_addr=2, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=320, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=192, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=64, vtile_id=0, send_width=16, target_addr=2, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=336, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=208, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=80, vtile_id=0, send_width=16, target_addr=2, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=352, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=224, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=96, vtile_id=0, send_width=16, target_addr=2, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=400, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=368, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=416, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=432, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=448, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=464, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=480, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=528, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=512, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=496, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=544, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=560, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=576, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=592, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=608, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=656, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=640, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=624, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=672, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=688, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=704, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=720, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=736, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=784, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=768, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=752, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=800, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=816, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=832, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=848, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=864, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=912, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=896, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=880, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=928, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=944, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=960, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=976, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=992, vtile_id=0, send_width=16, target_addr=3, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_halt()
dict_list.append(i_temp.copy())
filename = 'lenet/tile0/tile_imem.npy'
np.save(filename, dict_list)
