
import sys, os
import numpy as np
import math
sys.path.insert (0, '/home/plinio/puma-simulator/include/')
sys.path.insert (0, '/home/plinio/puma-simulator/src/')
sys.path.insert (0, '/home/plinio/puma-simulator/')
from data_convert import *
from instrn_proto import *
from tile_instrn_proto import *
dict_temp = {}
dict_list = []
i_temp = i_receive(mem_addr=3456, vtile_id=0, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=2, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=3328, vtile_id=0, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=2, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=3200, vtile_id=0, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=2, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=3072, vtile_id=0, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=2, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=14, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=14, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=14, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=14, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=26, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=26, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=26, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=26, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=38, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=38, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=38, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=38, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=51, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=51, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=51, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=51, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=63, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=63, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=63, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=63, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=75, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=75, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=75, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=75, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=87, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=87, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=87, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=87, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=100, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=100, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=100, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=100, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=112, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=112, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=112, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=112, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=124, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=124, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=124, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=124, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=136, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=136, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=136, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=136, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=149, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=149, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=149, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=149, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=161, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=161, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=161, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=161, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=173, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=173, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=173, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=173, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=185, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=185, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=185, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=185, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=198, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=198, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=198, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=198, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=210, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=210, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=210, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=210, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=222, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=222, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=222, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=222, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=234, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=234, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=234, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=234, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=247, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=247, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=247, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=247, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=259, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=259, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=259, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=259, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=271, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=271, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=271, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=271, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=283, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=283, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=283, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=283, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=296, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=296, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=296, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=296, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=308, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=308, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=308, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=308, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=320, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=320, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=320, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=320, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=332, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=332, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=332, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=332, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=345, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=345, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=345, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=345, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=357, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=357, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=357, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=357, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2816, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2688, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2560, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2432, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2304, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2176, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2048, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1920, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1792, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1664, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1536, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1408, vtile_id=393, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=384, vtile_id=381, send_width=16, target_addr=369, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=256, vtile_id=381, send_width=16, target_addr=369, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=128, vtile_id=381, send_width=16, target_addr=369, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=0, vtile_id=381, send_width=16, target_addr=369, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2944, vtile_id=380, receive_width=16, counter=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=3584, vtile_id=381, send_width=16, target_addr=1, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_send(mem_addr=1280, vtile_id=381, send_width=16, target_addr=382, vec=8)
dict_list.append(i_temp.copy())
i_temp = i_halt()
dict_list.append(i_temp.copy())
filename = 'vgg16/tile381/tile_imem.npy'
np.save(filename, dict_list)
