
import sys, os
import numpy as np
import math
sys.path.insert (0, '/home/plinio/puma-simulator/include/')
sys.path.insert (0, '/home/plinio/puma-simulator/src/')
sys.path.insert (0, '/home/plinio/puma-simulator/')
from data_convert import *
from instrn_proto import *
from tile_instrn_proto import *
dict_temp = {}
dict_list = []
i_temp = i_receive(mem_addr=0, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=6, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=12, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=18, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=24, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=30, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=36, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=42, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=48, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=54, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=60, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=66, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=72, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=78, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=84, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=90, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=96, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=102, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=108, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=114, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=120, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=126, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=132, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=138, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=144, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=150, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=156, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=162, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=168, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=174, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=180, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=186, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=192, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=198, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=204, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=210, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=216, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=222, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=228, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=234, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=240, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=246, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=252, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=258, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=264, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=270, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=276, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=282, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=288, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=294, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=300, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=306, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=312, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=318, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=324, vtile_id=3, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=330, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=336, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=342, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=348, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=354, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=360, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=366, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=372, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=378, vtile_id=2, receive_width=6, counter=1, vec=1)
dict_list.append(i_temp.copy())
i_temp = i_halt()
dict_list.append(i_temp.copy())
filename = 'lenet/tile1/tile_imem.npy'
np.save(filename, dict_list)
