
import sys, os
import numpy as np
import math
sys.path.insert (0, '/home/plinio/puma-simulator/include/')
sys.path.insert (0, '/home/plinio/puma-simulator/src/')
sys.path.insert (0, '/home/plinio/puma-simulator/')
from data_convert import *
from instrn_proto import *
from tile_instrn_proto import *
dict_temp = {}
dict_list = []
i_temp = i_receive(mem_addr=0, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=32, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=64, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=96, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=128, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=160, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=192, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=224, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=256, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=288, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=320, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=352, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=384, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=416, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=448, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=480, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=512, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=544, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=576, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=608, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=640, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=672, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=704, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=736, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=768, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=800, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=832, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=864, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=896, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=928, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=960, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=992, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1024, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1056, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1088, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1120, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1152, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1184, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1216, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1248, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1280, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1312, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1344, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1376, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1408, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1440, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1472, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1504, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1536, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1568, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1600, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1632, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1664, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1696, vtile_id=3, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1728, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1760, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1792, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1824, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1856, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1888, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1920, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1952, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1984, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2016, vtile_id=2, receive_width=16, counter=1, vec=2)
dict_list.append(i_temp.copy())
i_temp = i_halt()
dict_list.append(i_temp.copy())
filename = 'lenet/tile1/tile_imem.npy'
np.save(filename, dict_list)
