
import sys, os
import numpy as np
import math
sys.path.insert (0, '/home/plinio/puma-simulator/include/')
sys.path.insert (0, '/home/plinio/puma-simulator/src/')
sys.path.insert (0, '/home/plinio/puma-simulator/')
from data_convert import *
from instrn_proto import *
from tile_instrn_proto import *
dict_temp = {}
dict_list = []
i_temp = i_receive(mem_addr=0, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=64, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=128, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=192, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=256, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=320, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=384, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=448, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=512, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=576, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=640, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=704, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=768, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=832, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=896, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=960, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1024, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1088, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1152, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1216, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1280, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1344, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1408, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1472, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1536, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1600, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1664, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1728, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1792, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1856, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1920, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=1984, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2048, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2112, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2176, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2240, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2304, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2368, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2432, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2496, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2560, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2624, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2688, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2752, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2816, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2880, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=2944, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=3008, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_receive(mem_addr=3072, vtile_id=2, receive_width=16, counter=1, vec=4)
dict_list.append(i_temp.copy())
i_temp = i_halt()
dict_list.append(i_temp.copy())
filename = 'vgg16/tile1/tile_imem.npy'
np.save(filename, dict_list)
